<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fbLVDT" Id="{bb059efb-54fb-4fee-9451-10b597ccd0c6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbLVDT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbLVDT">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>